version: '3.8'

services:
  ml-app-datathon:
    build: .
    container_name: ml-app-datathon-container

    volumes:
      - .:/app
    
    ports:
      - "8888:8888"

    command: >
      python -m notebook
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --allow-root 
      --NotebookApp.token='' 
      --NotebookApp.password=''

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]