version: '3.8'

services:
  ml-app-datathon:
    build: .
    container_name: ml-app-datathon-container

    volumes:
      - .:/app

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]